services:
  - type: web
    name: frontend
    env: docker
    buildCommand: docker build -t frontend ./frontend
    startCommand: docker run frontend
    
  - type: web
    name: backend
    env: docker
    buildCommand: docker build -t backend ./backend
    startCommand: docker run backend 